---

- name: Give Marathon time to start its restart process
  wait_for:
    timeout: 30
  delegate_to: localhost
  become: false

- name: Delete Marathon ZK Migration in progress key if present and we didn't ask for an upgrade
  znode:
    hosts: "{{ docker_hostname }}:2181"
    name: /marathon/state/migration-in-progress
    state: absent


