---
- name: Install python3 pip
  yum:
    name: python3-pip
    state: present
  tags:
    - eod

- name: Install gdown for remote download
  shell: pip3 install gdown
  tags:
    - eod

- name: Use gdown to download file
  shell: /usr/local/bin/gdown https://drive.google.com/uc?id=1zBw9zmt65pfyA7dkuJlSPEscTYO8ZOc0 -O /tmp/ecs-13.8.9-linux-x64.bin 
  tags:
    - eod
  
- name: Chmod EOD binary
  file:
    path: "/tmp/{{ eod_installer }}"
    mode: a+x
  when: custom_repo
  tags:
    - eod

- name: Ensure that eod directory exists
  file:
    path: "{{ eod_install_directory }}"
    state: directory
  tags:
    - eod

- name: Copy the eod expect script
  template:
    src: install_eod_server.exp
    dest: /tmp/install_eod_server.exp
    mode: a+x
  tags:
    - eod

- name: run EOD expect script
  shell: /tmp/install_eod_server.exp
  when: custom_repo
  tags:
    - eod

- name: run eod silent install
  shell: "{{ eod_install_directory }}/bin/install -s"
  when: custom_repo
  args:
    creates: "{{ eod_install_directory }}/bin/otecs"
  tags:
    - eod
