---
install_r_packages: true

r_dependencies:
  - libcurl-devel
  - libxml2-devel
  - openssl-devel
  - hunspell-devel
  - udunits2
  - udunits2-devel
  - openmpi
  - openmpi-devel
  - openmpi-1.8-devel

r_packages:
  - "devtools"

r_packages_github:
  - name: shinydashboard
    user: rstudio

r_packages_with_opts:
  - name: udunits2
    include: /usr/include/udunits2
    lib: /usr/lib64

r_system_package_dir:
  - /usr/lib64/R/library
  - /usr/share/doc

r_packages_versioned:
  - name: pbdMPI
    version: 0.3-8
