# deploy_admin_terminal.yml
---
- hosts: db_terminal
  become: yes
  become_method: sudo

  roles:
    - {role: puppet_disable, when: "disable_puppet"}
    - {role: iptables, when: "iptables_config"}
    - common
    - {role: epel7, when: "use_epel and not 'production' in group_names"}
    - umask
    - jdk
    - postgresql-client
    - eod
    - devtools7
    - python2rh7
    - python3rh7
    - python-libs7
    - sqitch
    - {role: pem-client, tags: pem-client}
    - sublime
    - odbc7
  tasks:

    - name: Install needed packages
      yum:
        name: 
          - htop
          - screen
          - rsync
          - unzip
          - gpg
          - pigz
          - facter
          - sysstat
          - systemtap
          - ant # sar, iostat, vmstat
          - p7zip
          - p7zip-plugins
          - libpng12
          - tesseract
        state: present

    - name: Install custom packages
      yum:
        name: "{{ item }}"
        state: "{{ db_automation_package_state }}"
        disable_gpg_check: yes
      with_items: "{{ db_automation_custom_packages }}"

  #      - https://github.com/Factual/drake
  #      - https://github.com/audreyr/cookiecutter
  #       sudo yum install perl-devel perl-CPAN && curl -L http://cpanmin.us | perl - --sudo App::cpanminus
  #       http://hammerora.sourceforge.net/download.html
  #       - ogr2ogr in GDAL
