# deploy_admin_terminal.yml
---
- hosts: admin_terminal
  become: yes
  become_method: sudo
  roles:
    - { role: puppet_disable, when: "disable_puppet" }
    - { role: iptables, when: "iptables_config" }
    - common
    - { role: epel7, when: "use_epel and not 'production' in group_names" }
  #  - { role: python, when: "install_python and custom_repo" }
    - eod
    - devtools7
    - python2rh7
    - python3rh7
    - python-libs7
    - odbc7

  tasks:
    - name: Install development tools
      yum:
        name: "@development"
        state: present
        disable_gpg_check: yes

# TODO: Removing for now, since this needs modification to support both the old
#       Python install and the SCL install.  And, we don't deploy Ansible code 
#       from here anyways.
#    - name: Install Ansible in Python 2.7
#      become: no
#      pip:
#        virtualenv_command: /usr/local/bin/virtualenv
#        virtualenv: ~/.virtualenvs/data-platform
#        name: ansible
#        state: present
#        umask: "0022"
#      when: "install_python"
