---
- name: Get clouseau code
  git:
    repo: https://github.com/cfpb/clouseau
    dest: /opt/clouseau
    force: yes
  tags:
    -python2

#- name: Create links
#  file:
#    path: "/usr/local/bin/{{ item }}"
#    src: "/opt/clouseau/bin/{{ item }}"
#    state: link
#  with_items:
#    - clouseau
#    - clouseau_thin

- name: Install clouseau
  pip:
    executable: "{{ python_pip_bin }}"  # /opt/rh/python27/root/usr/bin/pip2.7
    name: /opt/clouseau
  environment:
    LD_LIBRARY_PATH: "{{ python_scl_pip_ld_path }}"  # scl python2.7 doesn't have the library path included 
  when: install_python
  tags:
    -python2
