# main.yml - Install Python 2.7 and Packages from RedHat Satellite
---
- name: Install Python2 packages (non scl)
  yum:
    name:
        - python2-pip
        - python2-virtualenv

- name: Install Python27 packages
  yum:
    name: 
      - python27
      - python27-PyYAML
      - python27-python-setuptools # python27-python-six
      - python27-python-devel
      - python27-python-libs
      - python27-python-pip
      - python27-python-psycopg2
      - python27-numpy
      - python27-scipy
      - python27-python-tools
      - python27-tkinter
      - python27-python-virtualenv
    state: present

- name: SCL Enable Pip Install Upgrade Pip 
  shell: |
    scl enable python27 -- pip install --upgrade pip==20.3.4
  become: yes
  become_method: sudo

- name: SCL Enable Pip Install numpy, scipy
  shell: |
    scl enable python27 -- pip install numpy scipy 
  become: yes
  become_method: sudo

- name: Make python 2.7 the default python for this machine
  template:
      src: scl_enable_python27.sh.j2
      dest: /etc/profile.d/scl_enable_python27.sh
  when: set_python27_default_python | bool
