# main.yml
---
- name: restart zookeeper
  service:
    name: zookeeper-server
    state: restarted

- name: restart mesos-master
  service:
     name: mesos-master
     state: restarted

- name: restart marathon agent
  command: restart marathon
  listen: restart marathon

- name: Give Marathon time to start its restart process
  include_tasks: post_deploy_mesos_master.yml
  listen: restart marathon 
  when: not marathon_upgrade
