# main.yml
---
- name: restart zookeeper
  systemd:
    name: zookeeper-server
    state: restarted

- name: restart mesos-master
  systemd:
     name: mesos-master
     state: restarted

- name: restart marathon agent
  systemd:
     name: marathon
     state: restarted
  listen: restart marathon

- name: Give Marathon time to start its restart process
  include_tasks: post_deploy_mesos_master.yml
  listen: restart marathon 
  when: not marathon_upgrade
